SOURCES +=src/flv/lang/Number.cpp src/flv/lang/String.cpp src/flv/lang/Struct.cpp  src/flv/lang/ECMAArray.cpp 
	
#OBJS +=src/flv/lang/Number.o src/flv/lang/String.o src/flv/lang/Struct.o src/flv/lang/ECMAArray.o 
	